import { StyleSheet } from 'react-native'

export const buttons = StyleSheet.create({
    metricsButton: {
        padding: 10,
        borderRadius: 20,
        marginTop: 20,
        marginBottom: 10,
        borderWidth: 1,
        width: '95%',
        color: 'white',
        backgroundColor: '#03254E',
        elevation: 4,
    },
    startButton: {
        padding: 10,
        borderRadius: 20,
        borderWidth: 1,
        width: '50%',
        backgroundColor: '#03254E',
        elevation: 4,
    },
    saveButton: {
        padding: 10,
        borderRadius: 20,
        marginHorizontal: 20,
        marginVertical: 10,
        width: '20%',
        backgroundColor: '#00A352',
        borderWidth: 1,
        alignSelf: 'flex-end',
        elevation: 4,
    },
    navButtons: {
        height: '100%',
        width: '33%',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#fff",
        elevation: 4,
    },
    darkNavButtons: {
        height: '100%',
        width: '33%',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#092635",
        elevation: 4,
    },
    deleteButton: {
        padding: 8,
        borderRadius: 20,
        marginTop: 20,
        backgroundColor: '#FF6542',
        borderWidth: 1,
        elevation: 5,
    },
    unPinButton: {
        padding: 8,
        borderTopRightRadius: 9,
        backgroundColor: '#FF6542',
        borderBottomWidth: 1,        
    },
    pinSaveButton: {
        padding: 8,
        borderBottomRightRadius: 9,
        backgroundColor: '#00A352',
        borderTopWidth: 1,    
    },
    pinButton: {
        padding: 8,
        borderRadius: 20,
        marginTop: 20,
        backgroundColor: '#E3B23C',
        borderWidth: 1,
        elevation: 5,
    },
    whiteButtonText: {
        fontSize: 22,
        color: 'white',
        textAlign: 'center',
    },
    blackButtonText: {
        fontSize: 22,
        color: '#001021',
        textAlign: 'center',
    },
    refreshButton:{
        padding: 10,
        borderRadius: 20,
        marginHorizontal: 20,
        marginVertical: 10,
        borderWidth: 1,
        width: '25%',
        color: 'white',
        backgroundColor: '#03254E',
        alignSelf: 'flex-end',
        elevation: 4,
    }
});