import { StyleSheet } from 'react-native';

export const darkStyles = StyleSheet.create({
dropDownTextContainer: {  
  padding: 10,
  fontStyle: 'italic',
  backgroundColor: '#5C8374',
  borderRadius: 15,
  margin: 15,
  elevation: 4,
},
topBar:{
  height: '7%',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: "#183D3D",
},
dataContainer:{
  height: 250,
  width: '30%',
  overflow: 'hidden',
  backgroundColor: '#092635',
  justifyContent: 'flex-end',
  marginHorizontal: 5,
  borderRadius: 60,
  borderWidth:2.5,
  elevation: 4,
},
navBar: {
  height: '10%',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: "#183D3D",
},
displayBox: {
  flex: 1,
  flexDirection: 'column',
  width: '100%',
  backgroundColor: '#092635',
},
dropDownBox: {
  width: '95%',
  alignSelf: 'center',
  backgroundColor: "#183D3D",
  margin: 20,
  borderRadius: 15,
  elevation: 10,
},
smallInfoBox: {
  width: '95%',
  height: 50,
  backgroundColor: '#183D3D',
  borderRadius: 15,
  justifyContent: 'center',
  marginTop: 10,
},
mediumInfoBox: {
  display: 'flex',
  flexDirection: 'row',
  width: '95%',
  height: 270,
  borderRadius: 5, 
  backgroundColor: '#183D3D',
  justifyContent: 'space-around',
  alignItems: 'center',
  marginTop: 20,
  elevation: 4,
},
metricInfoBox: {
  display: 'flex',
  width: '45%',
  justifyContent: 'space-evenly',
  alignItems: 'center',
  borderRadius: 10, 
  backgroundColor: '#183D3D',
  marginTop: 20,
  borderWidth: 1,
  elevation: 4,
},
pinnedInfoBox: {
  display: 'flex',
  flexDirection: 'row', 
  alignSelf: 'center',
  width: '95%',
  height: 300,
  borderRadius: 10, 
  backgroundColor: '#183D3D',
  marginTop: 25,
  marginBottom:20,
  borderWidth: 1,
  overflow: 'hidden',
  elevation: 4,
},
statusBox: {
  backgroundColor: '#183D3D',
  justifyContent: 'center',
  width: '30%',
  borderRadius: 22,
  elevation: 4,
},
pinnedButtonBox: {
  width: '25%',
  display: 'flex',
  flexDirection: 'column',
  justifyContent:'space-between',
  backgroundColor: '#B4CDCF',
},
block: {
  height: 50,
  justifyContent: 'center',
  backgroundColor: '#092635',
},
selectedText: {
  fontSize: 20,
  padding: 10,
  color: '#ffff',
  textAlign: 'center',
  backgroundColor: '#092635',
  opacity: 0.5
},
subHeadingText: {
  fontSize: 22,
  textAlign: 'center',
  color: '#ffff',
},
statusText: {
  fontSize: 20,
  padding: 10,
  textAlign: 'center',
  justifyContent: 'center',
  color: 'white',
},
headingText: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#ffff',
},
pinnedText: {
  fontSize: 22,
  textAlign: 'center',
  color: '#ffff',
},
metricTextTitle: {
  fontSize: 19,
  textAlign: 'center',
  fontWeight: 'bold',
  color: '#ffff',
},
metricText: {
  fontSize: 15,
  textAlign: 'center',
  color: '#ffff',
},
});