import { StyleSheet } from 'react-native';
import  Constants  from 'expo-constants';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      paddingTop: Constants.statusBarHeight,
    },
    controlContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    topBar:{
      height: '10%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: "red",
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20
    },
    displayBox: {
      flex: 1,
      flexDirection: 'column',
      width: '100%',
    },
    navBar: {
      height: '10%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: "#f4f4f4",
    },
    navContainer: {
      display: 'flex',
      flexDirection: 'row',
      width: '100%',
      justifyContent:'space-around',
    },
    headingBox:{
      width: '95%',
      height: 50,
      justifyContent: 'center',
      borderRadius: 22,
      marginTop: 20,
    },
    smallInfoBox: {
      width: '95%',
      height: 50,
      backgroundColor: 'lightgrey',
      justifyContent: 'center',
      marginTop: 10,
    },
    dataTemperatureContainer:{
      height: 250,
      width: '30%',
      overflow: 'hidden',
      backgroundColor: 'white',
      justifyContent: 'flex-end',
      borderRadius: 60,
      borderWidth:2
    },
    dataHumidityContainer: {
      height: 250,
      width: '30%',
      overflow: 'hidden',
      backgroundColor: 'white',
      justifyContent: 'flex-end',
      borderRadius: 10,
      borderWidth:1,
      borderTopLeftRadius: 60,
      borderTopRightRadius: 60,
    },
    textDataContainer:{
      height: 250,
      width: '50%',
      justifyContent: 'space-evenly',
    },
    mediumInfoBox: {
      display: 'flex',
      flexDirection: 'row',
      width: '95%',
      height: 300,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
      backgroundColor: 'lightgrey',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginTop: 20,
      borderTopWidth: 3,
    },
    mediumInfoBox: {
      display: 'flex',
      flexDirection: 'row',
      width: '95%',
      height: 300,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
      backgroundColor: 'lightgrey',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginTop: 20,
      borderTopWidth: 3,
    },
    statusBox: {
      backgroundColor: 'lightgrey',
      justifyContent: 'center',
      width: '30%',
      borderRadius: 22,
    },
    mercury: {
      backgroundColor: 'darkred',
    }, 
    headingText: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    subHeadingText: {
      fontSize: 20,
      textAlign: 'center',
    },
    statusText: {
      fontSize: 20,
      padding: 10,
      textAlign: 'center',
      justifyContent: 'center',
      color: 'darkgreen',
    },
    block : {
      height: 100,
      justifyContent: 'center',
    },
    buttonRowContainer: { 
      width: '95%',
      marginTop: 25,
      marginBottom: 10,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
  },
  });